language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "pypy2.7"

install:
  - git config --global user.email "bumpversion-test-git@travis.ci"
  - git config --global user.name "Testing Git on Travis CI"
  - git --version
  - git config --list
  - echo -e '[ui]\nusername = Testing Mercurial on Travis CI <bumpversion-test-hg@travis.ci>' > ~/.hgrc
  - hg --version
  - pip install --upgrade pytest tox-travis

script:
  - tox

